apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv-volume
  namespace: free5gc
  labels:
    type: local
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/"
