apiVersion: v1
kind: ConfigMap
metadata:
  name: amf-conf
  namespace: free5gc
data:
  config.file: |
    ### For reference, see `free5gc.conf`

    db_uri: mongodb://mongodb-svc/free5gc
    
    logger:
        file: /root/kube5gc/docker/free5gc/install/var/log/free5gc/amf.log
        trace: 
            app: 1
            s1ap: 1
            nas: 1
            diameter: 1
            gtp: 1
            pfcp: 1
            sbi: 1
    
    parameter:
        no_ipv6: true
    
    amf:
        freeDiameter: amf.conf
    
        s1ap:
          addr: 192.188.2.2
    
        gummei: 
          plmn_id:
            mcc: 208
            mnc: 93
          mme_gid: 1
          mme_code: 1
    
        tai:
          plmn_id:
            mcc: 208
            mnc: 93
          tac: 1
    
        security:
            integrity_order : [ EIA1, EIA2, EIA0 ]
            ciphering_order : [ EEA0, EEA1, EEA2 ]
    
        network_name:
            full: free5GC
    
    smf:
        http:
          addr: 192.168.0.3
          port: 8080
