apiVersion: apps/v1
kind: Deployment
metadata:
  name: hss-free5gc-deployment
  namespace: free5gc
  labels:
    app: free5gc-hss
spec:
  replicas: 1
  selector:
    matchLabels:
      app: free5gc-hss
  template:
    metadata:
      labels:
        app: free5gc-hss
    spec:
      containers:
      - name: free5gc-hss
        image: tw0927041027/free5gc-base:latest
        imagePullPolicy: Always
        command: ["/bin/sh"]
        args: ["-c", "/root/free5gc/install/bin/nextepc-hssd"]
        env:
        - name: DB_URI
          value: mongodb://mongodb-svc/free5gc
        volumeMounts:
        - name: config-volume
          mountPath: /root/free5gc/install/etc/free5gc/free5gc.conf
          subPath: free5gc.conf
        - name: freediameter-volume
          mountPath: /root/free5gc/install/etc/free5gc/freeDiameter/hss.conf
          subPath: hss.conf
        securityContext:
          privileged: true
      initContainers:
      - name: init-network-client
        image: sdnvortex/network-controller:v0.4.9
        command: ["/go/bin/client"]
        args: ["-s=unix:///tmp/vortex.sock", "-b=br0", "-n=eth1", "-i=192.188.2.4/24"]
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_UUID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        volumeMounts:
        - mountPath: /tmp/
          name: grpc-sock
      volumes:
      - name: grpc-sock
        hostPath:
          path: /tmp/vortex/
      - name: config-volume
        configMap:
          name: free5gc-config
          items:
          - key: free5gc.conf
            path: free5gc.conf
      - name: freediameter-volume
        configMap:
          name: free5gc-config
          items:
          - key: hss.conf
            path: hss.conf
