apiVersion: v1
kind: ConfigMap
metadata:
  name: upf-config
  namespace: free5gc
data:
  config.file: |
    ### For reference, see `free5gc.conf`
    
    logger:
        file: /root/kube5gc/docker/free5gc/install/var/log/free5gc/upf.log
        trace: 
            app: 1
            diameter: 1
            gtpv2: 1
            gtp: 1
    
    parameter:
    
    upf:
        pfcp:
          addr:
            - 192.168.0.8
            - ::1
    
        gtpu:
          - addr: 192.188.2.2
          - addr: ::1
    
        ue_pool:
          - addr: 45.45.0.1/16
          - addr: cafe::1/64
    
        dns:
          - 8.8.8.8
          - 8.8.4.4
          - 2001:4860:4860::8888
          - 2001:4860:4860::8844
    
