apiVersion: v1
kind: ConfigMap
metadata:
  name: hss-config
  namespace: free5gc
data:
  config.file: |
    ### For reference, see `free5gc.conf`
    
    db_uri: mongodb://mongodb-svc/free5gc
    
    logger:
        file: /root/kube5gc/docker/free5gc/install/var/log/free5gc/hss.log
        trace: 
            app: 1
            diameter: 1
    
    parameter:
    
    hss:
        freeDiameter: hss.conf
